//! Markdown report generator

use anyhow::Result;
use std::path::Path;
use super::ScanResults;

/// Generate markdown report
pub fn generate_markdown_report(results: &ScanResults, path: &Path) -> Result<()> {
    let mut md = String::new();
    let breakdown = results.severity_breakdown();

    // Header
    md.push_str("# Shield️ HyperionScan Security Report\n\n");

    // Metadata
    md.push_str("## Scan Information\n\n");
    md.push_str(&format!("| Property | Value |\n"));
    md.push_str(&format!("|----------|-------|\n"));
    md.push_str(&format!("| **Scan ID** | `{}` |\n", results.scan_id));
    md.push_str(&format!("| **Target** | `{}` |\n", results.target));
    md.push_str(&format!("| **Timestamp** | {} |\n", results.timestamp.format("%Y-%m-%d %H:%M:%S UTC")));
    md.push_str(&format!("| **Files Scanned** | {} |\n", results.files_scanned));
    md.push_str(&format!("| **Total Findings** | {} |\n", results.findings.len()));
    md.push_str(&format!("| **Risk Score** | {}/100 |\n\n", results.risk_score()));

    // Summary
    md.push_str("## Summary\n\n");
    md.push_str("| Severity | Count |\n");
    md.push_str("|----------|-------|\n");
    md.push_str(&format!("| Critical Critical | {} |\n", breakdown.critical));
    md.push_str(&format!("| High High | {} |\n", breakdown.high));
    md.push_str(&format!("| Medium Medium | {} |\n", breakdown.medium));
    md.push_str(&format!("| Low Low | {} |\n", breakdown.low));
    md.push_str(&format!("| Info Info | {} |\n\n", breakdown.info));

    // Category breakdown
    md.push_str("## Findings by Category\n\n");
    let categories = results.category_breakdown();
    for (category, count) in categories {
        md.push_str(&format!("- **{}**: {} findings\n", category, count));
    }
    md.push_str("\n");

    // Critical & High findings first
    if breakdown.critical > 0 || breakdown.high > 0 {
        md.push_str("## Alert Critical & High Severity Findings\n\n");
        md.push_str("> These findings require immediate attention.\n\n");

        for finding in &results.findings {
            if finding.severity == "critical" || finding.severity == "high" {
                md.push_str(&finding.to_markdown());
            }
        }
    }

    // Medium findings
    if breakdown.medium > 0 {
        md.push_str("## Warning Medium Severity Findings\n\n");

        for finding in &results.findings {
            if finding.severity == "medium" {
                md.push_str(&finding.to_markdown());
            }
        }
    }

    // Low & Info findings
    if breakdown.low > 0 || breakdown.info > 0 {
        md.push_str("## ℹ️ Low Severity & Informational\n\n");
        md.push_str("<details>\n<summary>Click to expand</summary>\n\n");

        for finding in &results.findings {
            if finding.severity == "low" || finding.severity == "info" {
                md.push_str(&finding.to_markdown());
            }
        }

        md.push_str("</details>\n\n");
    }

    // Rules triggered
    md.push_str("## Rules Triggered\n\n");
    for rule in results.unique_rules() {
        let count = results.findings.iter().filter(|f| f.rule_name == rule).count();
        md.push_str(&format!("- `{}` ({} occurrences)\n", rule, count));
    }
    md.push_str("\n");

    // Footer
    md.push_str("---\n\n");
    md.push_str("*Generated by [HyperionScan](https://github.com/hyperion-scan) - Local Security Scanner*\n");

    std::fs::write(path, md)?;
    Ok(())
}
